package com.platon.browser.dao.mapper;

import com.baomidou.mybatisplus.core.metadata.IPage;
import com.platon.browser.dao.entity.Delegation;
import com.platon.browser.dao.entity.DelegationExample;
import com.platon.browser.dao.entity.DelegationKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DelegationMapper {

    long countByExample(DelegationExample example);

    int deleteByExample(DelegationExample example);

    int deleteByPrimaryKey(DelegationKey key);

    int insert(Delegation record);

    int insertSelective(Delegation record);

    List<Delegation> selectByExample(DelegationExample example);

    /**
     * @param page    分页对象不能为空,入参IPage和返回结果IPage是同一个对象
     * @param example
     * @return com.baomidou.mybatisplus.core.metadata.IPage<com.platon.browser.dao.entity.Delegation>
     * @author huangyongpeng@matrixelements.com
     * @date 2021/4/25
     */
    IPage<Delegation> selectByExample(IPage<Delegation> page, DelegationExample example);

    Delegation selectByPrimaryKey(DelegationKey key);

    int updateByExampleSelective(@Param("record") Delegation record, @Param("example") DelegationExample example);

    int updateByExample(@Param("record") Delegation record, @Param("example") DelegationExample example);

    int updateByPrimaryKeySelective(Delegation record);

    int updateByPrimaryKey(Delegation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delegation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Delegation> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delegation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Delegation> list, @Param("selective") Delegation.Column... selective);

    /**
     * 删除成为历史的委托
     *
     * @param list
     * @return int
     * @author huangyongpeng@matrixelements.com
     * @date 2021/3/18
     */
    int batchDeleteIsHistory(@Param("list") List<Delegation> list);

}