package com.platon.browser.dao.mapper;

import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.platon.browser.dao.entity.TokenInventory;
import com.platon.browser.dao.entity.TokenInventoryExample;
import com.platon.browser.dao.entity.TokenInventoryKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TokenInventoryMapper {

    long countByExample(@Param("example") TokenInventoryExample example);

    int deleteByExample(@Param("example") TokenInventoryExample example);

    int deleteByPrimaryKey(TokenInventoryKey key);

    int insert(TokenInventory record);

    int insertSelective(TokenInventory record);

    /**
     * @param page    分页对象不能为空,入参IPage和返回结果IPage是同一个对象
     * @param example
     * @return com.baomidou.mybatisplus.core.metadata.IPage<com.platon.browser.dao.entity.TokenInventory>
     * @author huangyongpeng@matrixelements.com
     * @date 2021/4/25
     */
    IPage<TokenInventory> selectByExample(IPage<TokenInventory> page, @Param("example") TokenInventoryExample example);

    List<TokenInventory> selectByExample(@Param("example") TokenInventoryExample example);

    TokenInventory selectByPrimaryKey(TokenInventoryKey key);

    int updateByExampleSelective(@Param("record") TokenInventory record, @Param("example") TokenInventoryExample example);

    int updateByExample(@Param("record") TokenInventory record, @Param("example") TokenInventoryExample example);

    int updateByPrimaryKeySelective(TokenInventory record);

    int updateByPrimaryKey(TokenInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_inventory
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<TokenInventory> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_inventory
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<TokenInventory> list, @Param("selective") TokenInventory.Column... selective);

}