package com.platon.browser.dao.mapper;

import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.platon.browser.dao.entity.RpPlan;
import com.platon.browser.dao.entity.Vote;
import com.platon.browser.dao.entity.VoteExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface VoteMapper {

    long countByExample(VoteExample example);

    int deleteByExample(VoteExample example);

    int deleteByPrimaryKey(String hash);

    int insert(Vote record);

    int insertSelective(Vote record);

    /**
     * @param page    分页对象不能为空,入参IPage和返回结果IPage是同一个对象
     * @param example
     * @return com.baomidou.mybatisplus.core.metadata.IPage<com.platon.browser.dao.entity.Vote>
     * @author huangyongpeng@matrixelements.com
     * @date 2021/4/25
     */
    IPage<Vote> selectByExample(IPage<Vote> page, VoteExample example);

    List<Vote> selectByExample(VoteExample example);

    Vote selectByPrimaryKey(String hash);

    int updateByExampleSelective(@Param("record") Vote record, @Param("example") VoteExample example);

    int updateByExample(@Param("record") Vote record, @Param("example") VoteExample example);

    int updateByPrimaryKeySelective(Vote record);

    int updateByPrimaryKey(Vote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Vote> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Vote> list, @Param("selective") Vote.Column... selective);

}